"""empty message

Revision ID: 2bda1299ace1
Revises: 8363f00f6d04
Create Date: 2020-05-10 21:34:53.751401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bda1299ace1'
down_revision = '8363f00f6d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_title_author', 'books', ['title', 'author'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_title_author', 'books', type_='unique')
    # ### end Alembic commands ###
