"""empty message

Revision ID: 8363f00f6d04
Revises: 91588cab0cf8
Create Date: 2020-05-10 21:26:11.360068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8363f00f6d04'
down_revision = '91588cab0cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_title', table_name='books')
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.create_index('ix_books_title', 'books', ['title'], unique=True)
    # ### end Alembic commands ###
