"""empty message

Revision ID: f1ba073577a7
Revises: 2bda1299ace1
Create Date: 2020-05-10 22:32:02.419139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ba073577a7'
down_revision = '2bda1299ace1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_book', 'user_books', ['user_id', 'book_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_book', 'user_books', type_='unique')
    # ### end Alembic commands ###
